# Generated by Django 2.2b1 on 2019-06-08 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kakeibo', '0002_category_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_name', 'user')},
        ),
    ]
