# Generated by Django 2.2b1 on 2019-06-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0004_auto_20190609_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='blance_label',
            field=models.BooleanField(default=False, verbose_name='収支ラベル'),
        ),
    ]
