# Generated by Django 2.2b1 on 2019-06-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_category_blance_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='blance_label',
            new_name='balance_label',
        ),
    ]
