# Generated by Django 2.2b1 on 2019-06-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0006_auto_20190609_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='balance_label',
            field=models.IntegerField(choices=[(0, '支出'), (1, '収入')], default=0, verbose_name='収支ラベル'),
        ),
    ]
